- name: System install
  hosts: all
  tasks:
   - name: Installing system packages
     become: True
     ansible.builtin.apt:
      name:
        - vim
        - curl
        - tmux
        - suckless-tools
        - cmake
        - g++
        - feh


   - name: i3 build deps
     become: True
     ansible.builtin.apt:
       name:
        - libxcb1-dev 
        - libxcb-keysyms1-dev 
        - libpango1.0-dev
        - libxcb-util0-dev 
        - libxcb-icccm4-dev 
        - libyajl-dev
        - libstartup-notification0-dev 
        - libxcb-randr0-dev
        - libev-dev 
        - libxcb-cursor-dev 
        - libxcb-xinerama0-dev
        - libxcb-xkb-dev 
        - libxkbcommon-dev 
        - libxkbcommon-x11-dev
        - autoconf 
        - libxcb-xrm0 
        - libxcb-xrm-dev 
        - automake 
        - libxcb-shape0-dev
        - meson
   - name: Clone i3
     ansible.builtin.git:
       repo: https://github.com/i3/i3.git
       dest: ~/sources/i3
   - name: i3 build setup
     ansible.builtin.file:
       path: ~/sources/i3/build
       state: directory
   - name: Install i3
     ansible.builtin.shell: | 
       cd build
       meson ..
       sudo ninja install
     args:
       chdir: ~/sources/i3 

   - name: Copy i3 dotfiles
     copy: 
      src: ../dotfiles/i3
      dest: ~/.config/

   - name: Copy polybar dotfiles
     copy: 
      src: ../dotfiles/polybar
      dest: ~/.config/
   - name: Copy tmux dotfiles
     copy: 
      src: ../dotfiles/.tmux.conf
      dest: ~/
   
   - name: Polybar build deps
     become: True
     ansible.builtin.apt:
       name:
        - build-essential 
        - cmake-data 
        - pkg-config 
        - python3-sphinx 
        - python3-packaging 
        - libuv1-dev 
        - libcairo2-dev 
        - libxcb1-dev 
        - libxcb-util0-dev 
        - libxcb-randr0-dev 
        - libxcb-composite0-dev 
        - python3-xcbgen 
        - xcb-proto 
        - libxcb-image0-dev 
        - libxcb-ewmh-dev 
        - libxcb-icccm4-dev
        - libjsoncpp-dev


   - name: Clone polybar
     ansible.builtin.git:
       repo: https://github.com/polybar/polybar  
       dest: ~/sources/polybar
   - name: Polybar build setup
     ansible.builtin.file:
       path: ~/sources/polybar/build
       state: directory
   - name: Install polybar
     ansible.builtin.shell: | 
       cd build
       cmake ..
       make -j4
       sudo make install
     args:
       chdir: ~/sources/polybar 


   - name: Clone st
     ansible.builtin.git:
       repo: https://github.com/niwhsa9/st.git
       dest: ~/sources/st
   - name: St build setup
     ansible.builtin.file:
       path: ~/sources/st/build
       state: directory
   - name: Install st
     ansible.builtin.shell: | 
       sudo make install
     args:
       chdir: ~/sources/st 
